sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKcCUawnnLyZKgwTpvQ
    access-key-secret: SVu7A5Hvjl87RYHAXezMrjnk46nyAV
    bucket-name: sky-lailai
  redis:
    host: localhost
    port: 6379
    database: 10



